const AppConfig = {
  env: 'LIVE',
  bgm: [
    require('./assets/sound/bgm/bgm1.mp3'),
    require('./assets/sound/bgm/bgm2.mp3'),
    require('./assets/sound/bgm/bgm3.mp3'),
    require('./assets/sound/bgm/bgm4.mp3'),
    require('./assets/sound/bgm/bgmmain.mp3'),
    require('./assets/sound/bgm/bgm5.mp3'),
  ],
  unitBanner: 'ca-app-pub-8920089442341585/6368394810',
  unitInterstitial: 'ca-app-pub-8920089442341585/9652477823',
};

const homeAssets = {
  bgHomeImage: require('./assets/mainbg2.jpg'),
  bgRumput: require('./assets/maingrass.png'),
  animals: [
    {
      name: 'burung',
      image: require('./assets/home/burung.png'),
      animalSound: require('./assets/sound/suarahewan/burung.mp3'),
    },
    {
      name: 'gajah',
      image: require('./assets/home/gajah.png'),
      animalSound: require('./assets/sound/suarahewan/gajah.mp3'),
    },
    {
      name: 'jerapah',
      image: require('./assets/home/jerapah.png'),
      animalSound: require('./assets/sound/suarahewan/jerapah.mp3'),
    },
    {
      name: 'rusa',
      image: require('./assets/home/rusa.png'),
      animalSound: require('./assets/sound/suarahewan/rusa.mp3'),
    },
    {
      name: 'monyet',
      image: require('./assets/home/monyet.png'),
      animalSound: require('./assets/sound/suarahewan/monyet.mp3'),
    },
  ],
  openingVoice: [
    require('./assets/sound/opening1.mp3'),
    require('./assets/sound/suarahewan/gajah.mp3'),
    require('./assets/sound/suarahewan/monyet.mp3'),
  ],
  openingVoiceEnglish: [
    require('./assets/sound/opening-eng.mp3'),
    require('./assets/sound/suarahewan/kambing.mp3'),
    require('./assets/sound/suarahewan/anjing.mp3'),
  ],
};
const pageAssets = {
  bgImage: require('./assets/bgdetailscreen.jpg'),
  openingVoiceEnglish: require('./assets/sound/opening-eng2.mp3'),
  openingVoice: require('./assets/sound/opening2.mp3'),
};
const detailAssets = {
  bgImage: require('./assets/bgdetailscreen.jpg'),
};
const tebakGambarAssets = {
  bgImage: require('./assets/bgtebakhewan2.jpg'),
  grassTopLeft: require('./assets/grassimage/topleft.png'),
  grassTopRight: require('./assets/grassimage/topright.png'),
  grassBottomLeft: require('./assets/grassimage/bottomleft2.png'),
  grassBottomRight: require('./assets/grassimage/bottomright2.png'),
};
const tebakSuaraAssets = {
  tebakVoice: require('./assets/sound/tebaksuara.mp3'),
  tebakVoiceEng: require('./assets/sound/tebakhewan-eng.mp3'),
};
const iconButtons = {
  homeBtn: require('./assets/icon/homeimage.png'),
  backBtn: require('./assets/icon/backimage.png'),
  iconPohon: require('./assets/icon/pohon.png'),
};

const items = [
  {
    id: 'ayhi8',
    name: 'Ayam',
    image: require('./assets/animals/ayam-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/ayam.mp3'),
    soundName: require('./assets/sound/name/ayam.mp3'),
    soundNameEng: require('./assets/sound/name/ayam-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/ayam.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/ayam-eng.mp3'),
  },
  {
    id: 'b8374',
    name: 'Bebek',
    image: require('./assets/animals/bebek-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/bebek.mp3'),
    soundName: require('./assets/sound/name/bebek.mp3'),
    soundNameEng: require('./assets/sound/name/bebek-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/bebek.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/bebek-eng.mp3'),
  },
  {
    id: 'anj90',
    name: 'Anjing',
    image: require('./assets/animals/anjing-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/anjing.mp3'),
    soundName: require('./assets/sound/name/anjing.mp3'),
    soundNameEng: require('./assets/sound/name/anjing-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/anjing.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/anjing-eng.mp3'),
  },
  {
    id: 'ku254',
    name: 'Kucing',
    image: require('./assets/animals/kucing-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/kucing.mp3'),
    soundName: require('./assets/sound/name/kucing.mp3'),
    soundNameEng: require('./assets/sound/name/kucing-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/kucing.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/kucing-eng.mp3'),
  },
  {
    id: '33e9i',
    name: 'Kelinci',
    image: require('./assets/animals/kelinci-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/kelinci.mp3'),
    soundName: require('./assets/sound/name/kelinci.mp3'),
    soundNameEng: require('./assets/sound/name/kelinci-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/kelinci.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/kelinci-eng.mp3'),
  },
  {
    id: 'k1190',
    name: 'Kambing',
    image: require('./assets/animals/kambing-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/kambing.mp3'),
    soundName: require('./assets/sound/name/kambing.mp3'),
    soundNameEng: require('./assets/sound/name/kambing-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/kambing.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/kambing-eng.mp3'),
  },
  {
    id: 'o0901',
    name: 'Domba',
    image: require('./assets/animals/domba-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/domba.mp3'),
    soundName: require('./assets/sound/name/domba.mp3'),
    soundNameEng: require('./assets/sound/name/domba-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/domba.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/domba-eng.mp3'),
  },
  {
    id: 'bu349',
    name: 'Burung',
    image: require('./assets/animals/burung-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/burung.mp3'),
    soundName: require('./assets/sound/name/burung.mp3'),
    soundNameEng: require('./assets/sound/name/burung-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/burung.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/burung-eng.mp3'),
  },
  {
    id: '90s23',
    name: 'Sapi',
    image: require('./assets/animals/sapi-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/sapi.mp3'),
    soundName: require('./assets/sound/name/sapi.mp3'),
    soundNameEng: require('./assets/sound/name/sapi-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/sapi.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/sapi-eng.mp3'),
  },
  {
    id: 'm9928',
    name: 'Monyet',
    image: require('./assets/animals/monyet-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/monyet.mp3'),
    soundName: require('./assets/sound/name/monyet.mp3'),
    soundNameEng: require('./assets/sound/name/monyet-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/monyet.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/monyet-eng.mp3'),
  },
  {
    id: 'k1678',
    name: 'Kuda',
    image: require('./assets/animals/kuda-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/kuda.mp3'),
    soundName: require('./assets/sound/name/kuda.mp3'),
    soundNameEng: require('./assets/sound/name/kuda-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/kuda.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/kuda-eng.mp3'),
  },
  {
    id: '90jjk',
    name: 'Beruang',
    image: require('./assets/animals/beruang-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/beruang.mp3'),
    soundName: require('./assets/sound/name/beruang.mp3'),
    soundNameEng: require('./assets/sound/name/beruang-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/beruang.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/beruang-eng.mp3'),
  },
  {
    id: '445lk',
    name: 'Singa',
    image: require('./assets/animals/singa-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/singa.mp3'),
    soundName: require('./assets/sound/name/singa.mp3'),
    soundNameEng: require('./assets/sound/name/singa-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/singa.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/singa-eng.mp3'),
  },
  {
    id: 's9028',
    name: 'Serigala',
    image: require('./assets/animals/serigala-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/serigala.mp3'),
    soundName: require('./assets/sound/name/serigala.mp3'),
    soundNameEng: require('./assets/sound/name/serigala-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/serigala.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/serigala-eng.mp3'),
  },

  {
    id: 'bgj34',
    name: 'Badak',
    image: require('./assets/animals/badak-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/badak.mp3'),
    soundName: require('./assets/sound/name/badak.mp3'),
    soundNameEng: require('./assets/sound/name/badak-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/badak.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/badak-eng.mp3'),
  },
  {
    id: '1298a',
    name: 'Musang',
    image: require('./assets/animals/musang-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/musang.mp3'),
    soundName: require('./assets/sound/name/musang.mp3'),
    soundNameEng: require('./assets/sound/name/musang-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/musang.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/musang-eng.mp3'),
  },
  {
    id: 'u1290',
    name: 'Unta',
    image: require('./assets/animals/unta-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/unta.mp3'),
    soundName: require('./assets/sound/name/unta.mp3'),
    soundNameEng: require('./assets/sound/name/unta-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/unta.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/unta-eng.mp3'),
  },
  {
    id: 'rkl12',
    name: 'Rusa',
    image: require('./assets/animals/rusa-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/rusa.mp3'),
    soundName: require('./assets/sound/name/rusa.mp3'),
    soundNameEng: require('./assets/sound/name/rusa-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/rusa.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/rusa-eng.mp3'),
  },

  {
    id: '99ads',
    name: 'Tupai',
    image: require('./assets/animals/tupai-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/tupai.mp3'),
    soundName: require('./assets/sound/name/tupai.mp3'),
    soundNameEng: require('./assets/sound/name/tupai-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/tupai.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/tupai-eng.mp3'),
  },
  {
    id: 'zx901',
    name: 'Zebra',
    image: require('./assets/animals/zebra-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/zebra.mp3'),
    soundName: require('./assets/sound/name/zebra.mp3'),
    soundNameEng: require('./assets/sound/name/zebra-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/zebra.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/zebra-eng.mp3'),
  },
  {
    id: 'nk901',
    name: 'Kuda Nil',
    image: require('./assets/animals/kudanil-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/kudanil.mp3'),
    soundName: require('./assets/sound/name/kudanil.mp3'),
    soundNameEng: require('./assets/sound/name/kudanil-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/kudanil.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/kudanil-eng.mp3'),
  },
  {
    id: 'jr901',
    name: 'Jerapah',
    image: require('./assets/animals/jerapah-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/jerapah.mp3'),
    soundName: require('./assets/sound/name/jerapah.mp3'),
    soundNameEng: require('./assets/sound/name/jerapah-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/jerapah.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/jerapah-eng.mp3'),
  },
  {
    id: 'mc891',
    name: 'Harimau',
    image: require('./assets/animals/harimau-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/harimau.mp3'),
    soundName: require('./assets/sound/name/harimau.mp3'),
    soundNameEng: require('./assets/sound/name/harimau-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/harimau.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/harimau-eng.mp3'),
  },
  {
    id: 'ah98e',
    name: 'Gajah',
    image: require('./assets/animals/gajah-big.png'),
    soundAnimal: require('./assets/sound/suarahewan/gajah.mp3'),
    soundName: require('./assets/sound/name/gajah.mp3'),
    soundNameEng: require('./assets/sound/name/gajah-eng.mp3'),
    soundTebak: require('./assets/sound/tebakgambar/gajah.mp3'),
    soundTebakEng: require('./assets/sound/tebakgambar/gajah-eng.mp3'),
  },
];
const voiceTrue = [
  require('./assets/sound/betul.mp3'),
  require('./assets/sound/hebat.mp3'),
  require('./assets/sound/luarbiasa.mp3'),
];
const voiceTrueEng = [
  require('./assets/sound/correct.mp3'),
  require('./assets/sound/awesome.mp3'),
  require('./assets/sound/unbelievable.mp3'),
];
const voiceFalse = [
  require('./assets/sound/oow.mp3'),
  require('./assets/sound/cobalagi.mp3'),
  require('./assets/sound/cobalagi2.mp3'),
];
const voiceFalseEng = [
  require('./assets/sound/oow.mp3'),
  require('./assets/sound/tryagain.mp3'),
  require('./assets/sound/youcandoit.mp3'),
];

export {
  AppConfig,
  homeAssets,
  pageAssets,
  items,
  iconButtons,
  detailAssets,
  tebakGambarAssets,
  voiceFalse,
  voiceFalseEng,
  voiceTrue,
  voiceTrueEng,
  tebakSuaraAssets,
};
